name: Main Pipeline

env:
  GITHUB_REGISTRY: "ghcr.io"
  GITHUB_OWNER: "techyguy17"
  GITHUB_DOCKER_IMAGE: "home-assistant-freepbx-arm"

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2

      - name: Log into registry ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASS }} 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Build Docker
        working-directory: ./home-assistant-freepbx-arm
        run: |
          docker buildx build --platform linux/arm/v7 --no-cache -o type=docker -t $GITHUB_REGISTRY/$GITHUB_OWNER/$GITHUB_DOCKER_IMAGE:${{ env.SHA }} .
      - name: Publish Docker
        run: |
          docker push $GITHUB_REGISTRY/$GITHUB_OWNER/$GITHUB_DOCKER_IMAGE:${{ env.SHA }}